if: branch = v3.6
language: cpp
jobs:
  include:
    - os: linux
      arch: arm64
      env: OS_TYPE=fedora OS_VERSION=33 OS_ARCH=aarch64
    - os: linux
      arch: arm64
      env: OS_TYPE=centos OS_VERSION=8 OS_ARCH=aarch64
    - os: linux
      arch: amd64
      env: OS_TYPE=fedora OS_VERSION=33 OS_ARCH=x86_64
    - os: linux
      arch: amd64
      env: OS_TYPE=centos OS_VERSION=8 OS_ARCH=x86_64
services:
  - docker
install:
  - docker pull ${OS_TYPE}:${OS_VERSION}
  - docker run --name ctr -v ${PWD}:/sources -v ${PWD}:/output:Z ${OS_TYPE}:${OS_VERSION} dnf install gcc python27 boost-devel
  - docker run --name ctr sudo dnf groupinstall "Development Tools" "Development Libraries"
  - docker run --name ctr python2.7 -m ensurepip && docker exec ctr python2.7 -m pip install -r buildscripts/requirements.txt
script:
  - docker run --name ctr python2.7 buildscripts/scons.py --prefix=/output core --disable-warnings-as-errors
after_success:
  - docker run --name ctr strip /output/bin/mongo
  - docker run --name ctr strip /output/bin/mongos
  - docker run --name ctr strip /output/binmongod
