if: branch = v3.6
language: cpp
os: linux
dist: bionic
cache:
  pip: true
  ccache: true
  directories:
    - $TRAVIS_BUILD_DIR/build
stages:
  - Clean Cache
  - Compile Mongo
  - Compile Mongos
  - Compile Mongod
  - Compile Unit Tests
  - Compile DB Tests
  #- test
jobs:
  include:
    - stage: Clean Cache
      arch: arm64
      env: OS_ARCH=arm64
      install: skip
      script: rm -rf $TRAVIS_BUILD_DIR/build/*
    - stage: Clean Cache
      arch: amd64
      env: OS_ARCH=amd64
      install: skip
      script: rm -rf $TRAVIS_BUILD_DIR/build/*
    - stage: Compile Mongod
      arch: arm64
      env: OS_ARCH=arm64
      script: python2.7 buildscripts/scons.py -j4 mongod --disable-warnings-as-errors CCFLAGS=-march=armv8-a+crc
    - stage: Compile Mongos
      arch: arm64
      env: OS_ARCH=arm64
      script: python2.7 buildscripts/scons.py -j4 mongos --disable-warnings-as-errors CCFLAGS=-march=armv8-a+crc
    - stage: Compile Mongo
      arch: arm64
      env: OS_ARCH=arm64
      script: python2.7 buildscripts/scons.py -j4 mongo --disable-warnings-as-errors CCFLAGS=-march=armv8-a+crc
    - stage: Compile Unit Tests
      arch: arm64
      env: OS_ARCH=arm64
      script: python2.7 buildscripts/scons.py -j4 unittests --disable-warnings-as-errors CCFLAGS=-march=armv8-a+crc
    - stage: Compile DB Tests
      arch: arm64
      env: OS_ARCH=arm64
      script: python2.7 buildscripts/scons.py -j4 dbtest --disable-warnings-as-errors CCFLAGS=-march=armv8-a+crc
    - stage: Compile Mongod
      arch: amd64
      env: OS_ARCH=amd64
      script: python2.7 buildscripts/scons.py -j4 mongod --disable-warnings-as-errors
    - stage: Compile Mongos
      arch: amd64
      env: OS_ARCH=amd64
      script: python2.7 buildscripts/scons.py -j4 mongos --disable-warnings-as-errors
    - stage: Compile Mongo
      arch: amd64
      env: OS_ARCH=amd64
      script: python2.7 buildscripts/scons.py -j4 mongo --disable-warnings-as-errors
    - stage: Compile Unit Tests
      arch: amd64
      env: OS_ARCH=amd64
      script: python2.7 buildscripts/scons.py -j4 unittests --disable-warnings-as-errors
    - stage: Compile DB Tests
      arch: amd64
      env: OS_ARCH=amd64
      script: python2.7 buildscripts/scons.py -j4 dbtest --disable-warnings-as-errors
#    - stage: test
#      install: skip
#      script: skip
#services:
#  - docker
install:
  - sudo apt update
  - sudo apt install build-essential
  - sudo apt install python2.7 libpython2.7-dev python-pip libboost-filesystem-dev libboost-program-options-dev libboost-system-dev libboost-thread-dev
  - python2.7 -m pip install -r buildscripts/requirements.txt
#  - docker pull ${OS_TYPE}:${OS_VERSION}
#  - docker run -d -i --name ctr -v ${PWD}:/sources -v ${PWD}:/output:Z ${OS_TYPE}:${OS_VERSION} /bin/bash
#  - docker exec ctr dnf install -y gcc python27 boost-devel
#  - sudo apt update
#  - sudo apt install build-essential
#  - sudo apt install python2.7 libpython2.7-dev python-pip libboost-filesystem-dev libboost-program-options-dev libboost-system-dev libboost-thread-dev
#  - docker exec ctr dnf groupinstall -y development-libs development-tools
#  - docker exec ctr python2.7 -m ensurepip && docker exec ctr python2.7 -m pip install -r /sources/buildscripts/requirements.txt
#  - python2.7 -m pip install -r buildscripts/requirements.txt
#script:
#  - docker exec ctr /bin/bash -c "cd /sources && python2.7 /sources/buildscripts/scons.py --prefix=/output core --disable-warnings-as-errors"
#  - python2.7 buildscripts/scons.py -j4 all --disable-warnings-as-errors
#after_success:
#  - docker exec ctr strip /output/bin/mongo
#  - docker exec ctr strip /output/bin/mongos
#  - docker exec ctr strip /output/binmongod
